#ifndef __ASM_OFFSETS_H__
#define __ASM_OFFSETS_H__
/*
 * DO NOT MODIFY.
 *
 * This file was generated by Kbuild
 *
 */

#define TSK_ACTIVE_MM 176 /* offsetof(struct task_struct, active_mm)	@ */

#define TI_FLAGS 0 /* offsetof(struct thread_info, flags)	@ */
#define TI_PREEMPT 4 /* offsetof(struct thread_info, preempt_count)	@ */
#define TI_ADDR_LIMIT 8 /* offsetof(struct thread_info, addr_limit)	@ */
#define TI_TASK 12 /* offsetof(struct thread_info, task)	@ */
#define TI_EXEC_DOMAIN 16 /* offsetof(struct thread_info, exec_domain)	@ */
#define TI_CPU 20 /* offsetof(struct thread_info, cpu)	@ */
#define TI_CPU_DOMAIN 24 /* offsetof(struct thread_info, cpu_domain)	@ */
#define TI_CPU_SAVE 28 /* offsetof(struct thread_info, cpu_context)	@ */
#define TI_USED_CP 80 /* offsetof(struct thread_info, used_cp)	@ */
#define TI_TP_VALUE 96 /* offsetof(struct thread_info, tp_value)	@ */
#define TI_FPSTATE 288 /* offsetof(struct thread_info, fpstate)	@ */
#define TI_VFPSTATE 432 /* offsetof(struct thread_info, vfpstate)	@ */

#define S_R0 0 /* offsetof(struct pt_regs, ARM_r0)	@ */
#define S_R1 4 /* offsetof(struct pt_regs, ARM_r1)	@ */
#define S_R2 8 /* offsetof(struct pt_regs, ARM_r2)	@ */
#define S_R3 12 /* offsetof(struct pt_regs, ARM_r3)	@ */
#define S_R4 16 /* offsetof(struct pt_regs, ARM_r4)	@ */
#define S_R5 20 /* offsetof(struct pt_regs, ARM_r5)	@ */
#define S_R6 24 /* offsetof(struct pt_regs, ARM_r6)	@ */
#define S_R7 28 /* offsetof(struct pt_regs, ARM_r7)	@ */
#define S_R8 32 /* offsetof(struct pt_regs, ARM_r8)	@ */
#define S_R9 36 /* offsetof(struct pt_regs, ARM_r9)	@ */
#define S_R10 40 /* offsetof(struct pt_regs, ARM_r10)	@ */
#define S_FP 44 /* offsetof(struct pt_regs, ARM_fp)	@ */
#define S_IP 48 /* offsetof(struct pt_regs, ARM_ip)	@ */
#define S_SP 52 /* offsetof(struct pt_regs, ARM_sp)	@ */
#define S_LR 56 /* offsetof(struct pt_regs, ARM_lr)	@ */
#define S_PC 60 /* offsetof(struct pt_regs, ARM_pc)	@ */
#define S_PSR 64 /* offsetof(struct pt_regs, ARM_cpsr)	@ */
#define S_OLD_R0 68 /* offsetof(struct pt_regs, ARM_ORIG_r0)	@ */
#define S_FRAME_SIZE 72 /* sizeof(struct pt_regs)	@ */

#define VMA_VM_MM 0 /* offsetof(struct vm_area_struct, vm_mm)	@ */
#define VMA_VM_FLAGS 20 /* offsetof(struct vm_area_struct, vm_flags)	@ */

#define VM_EXEC 4 /* VM_EXEC	@ */

#define PAGE_SZ 4096 /* PAGE_SIZE	@ */

#define SYS_ERROR0 10420224 /* 0x9f0000	@ */

#define SIZEOF_MACHINE_DESC 52 /* sizeof(struct machine_desc)	@ */
#define MACHINFO_TYPE 0 /* offsetof(struct machine_desc, nr)	@ */
#define MACHINFO_NAME 12 /* offsetof(struct machine_desc, name)	@ */
#define MACHINFO_PHYSIO 4 /* offsetof(struct machine_desc, phys_io)	@ */
#define MACHINFO_PGOFFIO 8 /* offsetof(struct machine_desc, io_pg_offst)	@ */

#define PROC_INFO_SZ 52 /* sizeof(struct proc_info_list)	@ */
#define PROCINFO_INITFUNC 16 /* offsetof(struct proc_info_list, __cpu_flush)	@ */
#define PROCINFO_MM_MMUFLAGS 8 /* offsetof(struct proc_info_list, __cpu_mm_mmu_flags)	@ */
#define PROCINFO_IO_MMUFLAGS 12 /* offsetof(struct proc_info_list, __cpu_io_mmu_flags)	@ */

#define ctx_sizeof 1876 /* sizeof(NkOsCtx)	@ */
#define ctx_swi_off 8 /* offsetof(NkOsCtx, os_vectors[2])	@ */
#define ctx_irq_off 24 /* offsetof(NkOsCtx, os_vectors[6])	@ */
#define ctx_iirq_off 40 /* offsetof(NkOsCtx, os_vectors[10])	@ */
#define ctx_xirq_off 36 /* offsetof(NkOsCtx, os_vectors[9])	@ */
#define ctx_pending_off 132 /* offsetof(NkOsCtx, pending)	@ */
#define ctx_enabled_off 136 /* offsetof(NkOsCtx, enabled)	@ */
#define ctx_sp_svc_off 144 /* offsetof(NkOsCtx, sp_svc)	@ */
#define ctx_root_dir_off 156 /* offsetof(NkOsCtx, root_dir)	@ */
#define ctx_domain_off 160 /* offsetof(NkOsCtx, domain)	@ */
#define ctx_arch_id_off 232 /* offsetof(NkOsCtx, arch_id)	@ */
#define ctx_vil_off 164 /* offsetof(NkOsCtx, vil)	@ */
#define ctx_idle_off 300 /* offsetof(NkOsCtx, idle)	@ */
#define ctx_prio_set_off 304 /* offsetof(NkOsCtx, prio_set)	@ */
#define ctx_regs_r0_off 64 /* offsetof(NkOsCtx, regs[0])	@ */
#define ctx_regs_r4_off 80 /* offsetof(NkOsCtx, regs[4])	@ */
#define ctx_regs_r10_off 104 /* offsetof(NkOsCtx, regs[10])	@ */
#define ctx_regs_r12_off 112 /* offsetof(NkOsCtx, regs[12])	@ */
#define ctx_regs_sp_off 116 /* offsetof(NkOsCtx, regs[13])	@ */
#define ctx_regs_lr_off 120 /* offsetof(NkOsCtx, regs[14])	@ */
#define ctx_regs_pc_off 124 /* offsetof(NkOsCtx, regs[15])	@ */
#define ctx_regs_cpsr_off 128 /* offsetof(NkOsCtx, regs[16])	@ */
#define ctx_nkvector_off 152 /* offsetof(NkOsCtx, nkvector)	@ */

#endif
